services:
  backend:
    build: ./backend
    container_name: todo-backend
    ports:
      - "3001:3001"
    restart: always
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    container_name: todo-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always